// @ts-nocheck
import { useMemo, useState } from "react";
import { Building2, Layers, MapPin, Ruler } from "lucide-react";
import { RAW_DATA } from "./data/buildings";
import { downloadCsv, groupByCity, parseBuildings } from "./lib/buildingMap";
import { runValidation } from "./lib/validation";
import { TileWorldMap } from "./components/TileWorldMap";
import { StatCard } from "./components/StatsCards";
import { FilterPanel } from "./components/FilterPanel";
import { ClusterPanel } from "./components/ClusterPanel";
import { TablePanel } from "./components/TablePanel";

const buildings = parseBuildings(RAW_DATA);
if (import.meta.env.DEV) runValidation(buildings);

function barList(rows, labelKey, valueKey, color = "#2563eb") { const max = Math.max(...rows.map((row) => row[valueKey]), 1); return <div className="space-y-3">{rows.map((row) => <div key={row[labelKey]}><div className="mb-1 flex justify-between gap-4 text-xs text-slate-600"><span className="truncate">{row[labelKey]}</span><span className="font-medium">{row[valueKey]}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${(row[valueKey] / max) * 100}%`, backgroundColor: color }} /></div></div>)}</div>; }

export default function BatchGeoReplacementMap() {
const [query, setQuery] = useState(""); const [country, setCountry] = useState("All"); const [city, setCity] = useState("All"); const [material, setMaterial] = useState("All"); const [primaryFunction, setPrimaryFunction] = useState("All"); const [minHeight, setMinHeight] = useState(246); const [maxHeight, setMaxHeight] = useState(828); const [minYear, setMinYear] = useState(1931); const [maxYear, setMaxYear] = useState(2023); const [selectedLocation, setSelectedLocation] = useState("Dubai, United Arab Emirates");
const countries = useMemo(() => Array.from(new Set(buildings.map((row) => row.country))).sort(), []);
const countryOptions = useMemo(() => ["All", ...countries], [countries]);
const cityOptions = useMemo(() => { const scoped = country === "All" ? buildings : buildings.filter((row) => row.country === country); return ["All", ...Array.from(new Set(scoped.map((row) => row.city))).sort()]; }, [country]);
const materialOptions = useMemo(() => ["All", ...Array.from(new Set(buildings.map((row) => row.material))).sort()], []);
const functionOptions = useMemo(() => ["All", ...Array.from(new Set(buildings.map((row) => row.primaryFunction))).sort()], []);
const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); return buildings.filter((row) => { const searchable = `${row.name} ${row.city} ${row.country} ${row.material} ${row.function}`.toLowerCase(); return (!normalized || searchable.includes(normalized)) && (country === "All" || row.country === country) && (city === "All" || row.city === city) && (material === "All" || row.material === material) && (primaryFunction === "All" || row.primaryFunction === primaryFunction) && row.heightM >= minHeight && row.heightM <= maxHeight && row.completed >= minYear && row.completed <= maxYear; }); }, [query, country, city, material, primaryFunction, minHeight, maxHeight, minYear, maxYear]);
const cityGroups = useMemo(() => groupByCity(filtered), [filtered]);
const selectedGroup = cityGroups.find((group) => group.location === selectedLocation) ?? cityGroups[0] ?? null; const selectedBuilding = selectedGroup?.tallest ?? null;
const stats = useMemo(() => { const averageHeight = filtered.length ? Math.round(filtered.reduce((sum, row) => sum + row.heightM, 0) / filtered.length) : 0; const tallest = filtered.length ? Math.max(...filtered.map((row) => row.heightM)) : 0; return { buildings: filtered.length, cities: cityGroups.length, averageHeight, tallest }; }, [filtered, cityGroups]);
const countryBars = useMemo(() => { const counts = new Map(); filtered.forEach((row) => counts.set(row.country, (counts.get(row.country) ?? 0) + 1)); return Array.from(counts.entries()).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count).slice(0, 7); }, [filtered]);
const functionBars = useMemo(() => { const counts = new Map(); filtered.forEach((row) => counts.set(row.primaryFunction, (counts.get(row.primaryFunction) ?? 0) + 1)); return Array.from(counts.entries()).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count).slice(0, 7); }, [filtered]);
const decadeBars = useMemo(() => { const counts = new Map(); filtered.forEach((row) => { const decade = `${Math.floor(row.completed / 10) * 10}s`; counts.set(decade, (counts.get(decade) ?? 0) + 1); }); return Array.from(counts.entries()).map(([decade, count]) => ({ decade, count })).sort((a, b) => Number(a.decade.slice(0, 4)) - Number(b.decade.slice(0, 4))); }, [filtered]);
function resetFilters() { setQuery(""); setCountry("All"); setCity("All"); setMaterial("All"); setPrimaryFunction("All"); setMinHeight(246); setMaxHeight(828); setMinYear(1931); setMaxYear(2023); setSelectedLocation("Dubai, United Arab Emirates"); }
return <div className="min-h-screen bg-slate-50 p-4 text-slate-950 md:p-8"><div className="mx-auto max-w-7xl space-y-6"><section className="grid gap-4 md:grid-cols-4"><StatCard icon={<Building2 size={20} />} label="Buildings" value={stats.buildings} detail="Filtered structures currently in scope." /><StatCard icon={<MapPin size={20} />} label="Mapped cities" value={stats.cities} detail="Clusters preserve accurate city placement." /><StatCard icon={<Ruler size={20} />} label="Tallest" value={`${stats.tallest} m`} detail="Maximum height in the active view." /><StatCard icon={<Layers size={20} />} label="Average height" value={`${stats.averageHeight} m`} detail="Mean height across filtered records." /></section><FilterPanel resetFilters={resetFilters} onExport={downloadCsv} filtered={filtered} query={query} setQuery={setQuery} country={country} setCountry={setCountry} city={city} setCity={setCity} material={material} setMaterial={setMaterial} primaryFunction={primaryFunction} setPrimaryFunction={setPrimaryFunction} countryOptions={countryOptions} cityOptions={cityOptions} materialOptions={materialOptions} functionOptions={functionOptions} minHeight={minHeight} maxHeight={maxHeight} setMinHeight={setMinHeight} setMaxHeight={setMaxHeight} minYear={minYear} maxYear={maxYear} setMinYear={setMinYear} setMaxYear={setMaxYear} /><main className="grid gap-6 xl:grid-cols-[1fr_380px]"><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><TileWorldMap cityGroups={cityGroups} countries={countries} selectedGroup={selectedGroup} onSelectLocation={setSelectedLocation} /></section><aside className="space-y-5"><ClusterPanel selectedGroup={selectedGroup} selectedBuilding={selectedBuilding} /></aside></main><section className="grid gap-6 lg:grid-cols-3"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Buildings by country</h2>{barList(countryBars, "name", "count", "#2563eb")}</div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Primary function mix</h2>{barList(functionBars, "name", "count", "#059669")}</div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold">Completion decade</h2>{barList(decadeBars, "decade", "count", "#7c3aed")}</div></section><TablePanel filtered={filtered} setSelectedLocation={setSelectedLocation} /></div></div>;
}
